Ease listing contributors
OpenTermsArchive/deployment pull request #49
Opened 2024-06-17 09:31 UTC by clementbiron

Install and set up @all-contributors on this repository.

2024-06-18 14:29 UTC, MattiSG requested changes

2024-06-18 14:29 UTC, MattiSG commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
Nope 😉

2024-06-18 14:52 UTC, MattiSG approved these changes

2024-06-19 08:00 UTC, clementbiron commented
In consultation with the core team, I'm taking responsibility for bypassing the check_changelog test.

2024-06-19 08:01 UTC, merged