Update contributors
OpenTermsArchive/deployment pull request #50
Opened 2024-06-17 09:35 UTC by clementbiron

Hi @Harshil-Jani 

I am adding you to the list of contributors of this repository consolidated in the `.all-contributorsrc` file so that I can automatically list you on Open Terms Archive [about page](https://opentermsarchive.org/en/about/). The information used is the public information (name, login, avatar and profile URL) from your GitHub account. If you wish to correct any information or object to this addition, please let me know.

Thank you 🙏

@MattiSG that should be review and merge after https://github.com/OpenTermsArchive/deployment/pull/49

2024-06-18 14:25 UTC, MattiSG requested changes
Blocking: removal of enforcement address.

2024-06-18 14:25 UTC, MattiSG commented on .all-contributorsrc
> +      "name": "Martin Ratinaud. Freelancer.",
```suggestion
      "name": "Martin Ratinaud",
```

2024-06-18 14:25 UTC, MattiSG commented on CODE_OF_CONDUCT.md
> +[INSERT CONTACT METHOD].
Nope 😉

2024-06-20 15:28 UTC, MattiSG approved these changes

2024-06-20 15:28 UTC, MattiSG commented on .all-contributorsrc
> +        "doc"
```suggestion
        "code"
```

2024-06-24 14:10 UTC, clementbiron commented
In order to deliver, I'm taking responsibility for bypassing the changelog test.

2024-06-24 14:10 UTC, merged